# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{parseexcel}
  s.version = "0.5.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Hannes Wyss", "Hugh McGowan", "Pat Allan"]
  s.date = %q{2010-11-29}
  s.description = %q{A basic interface for parsing Excel files.}
  s.email = %q{pat@freelancing-gods.com}
  s.extra_rdoc_files = [
    "COPYING",
    "README"
  ]
  s.files = [
    "lib/parseexcel.rb",
    "lib/parseexcel/format.rb",
    "lib/parseexcel/olestorage.rb",
    "lib/parseexcel/parseexcel.rb",
    "lib/parseexcel/parser.rb",
    "lib/parseexcel/workbook.rb",
    "lib/parseexcel/worksheet.rb",
    "test/data/annotation.xls",
    "test/data/bar.xls",
    "test/data/comment.5.0.xls",
    "test/data/comment.xls",
    "test/data/dates.xls",
    "test/data/float.5.0.xls",
    "test/data/float.xls",
    "test/data/foo.xls",
    "test/data/image.xls",
    "test/data/nil.xls",
    "test/data/style.xls",
    "test/data/umlaut.5.0.xls",
    "test/data/umlaut.biff8.xls",
    "test/data/uncompressed.str.xls",
    "test/suite.rb",
    "test/test_format.rb",
    "test/test_olestorage.rb",
    "test/test_parser.rb",
    "test/test_workbook.rb",
    "test/test_worksheet.rb"
  ]
  s.homepage = %q{http://github.com/freelancing-god/parseexcel}
  s.rdoc_options = ["--main", "README"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Parse Excel Files}
  s.test_files = [
    "test/suite.rb",
    "test/test_format.rb",
    "test/test_olestorage.rb",
    "test/test_parser.rb",
    "test/test_workbook.rb",
    "test/test_worksheet.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

